# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 738d0a8c80f246354c84d5479735bb30d9adaf9ae8112151497123d1e13cce79e777b6a18aea01c6253765f60806fef3a00d361ce3afa6fd8929a6fbd346e8d5

test:
  secret_key_base: 6d04871649c3abd5305cd24cd7aeaa3ef9ae73715972cac2b5b1235bbdf188e4c2b1c7e81b20f390f19ca6e20125cfa11494a8cb61fd2158eda841906070c89e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 738d0a8c80f246354c84d5479735bb30d9adaf9ae8112151497123d1e13cce79e777b6a18aea01c6253765f60806fef3a00d361ce3afa6fd8929a6fbd346e8d5
