version: 2
jobs:
  deploy:
    machine: true
    working_directory: ~/circleci-2.0
    branch: master
    environment:
      - IMAGE_TAG: $CIRCLE_SHA1
    steps:    development:
      - ./deploy.sh:

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master